language: node_js
node_js:
- '0.12'
services:
- mongodb
- memcached
notifications:
  slack:
    secure: hhjFwxspabclpfnkVdjcHPP0X1juSHyF/kgppw2niWujluNazo2Dm2HmaVFkOIIHPEwjll/fiph6MvTBPMyj/YMMWGLwr/X4mJCasRyaaUXq8DLaEKfzEzLD/em/NNalACu05wGE7mZIqFFhtN6Pft2fNXVVNrfeNkfxvcyciuk=
deploy:
  provider: heroku
  api_key:
    secure: U0f8Xox5H140ay5YK+AW4y2AGT2hyetR7vna+YIE0oGm5KE+NsnRsORbCeqCblvUskdAROvGmEdyRW2+wQ57P2KkSlWpQuMjRTprR3NgP4u6QvsZHRPBPqefbyq3Y17cUXBfm0X5DqdRzyhqNe3UsjRIpT4IQaMtOoNI2nXsFUs=
  app: react-gyazz
  on:
    repo: shokai/react-gyazz
